# Generated by Django 5.2.8 on 2025-11-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0002_room_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
