# Generated by Django 5.2.8 on 2025-11-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris', '0003_alter_message_options_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Python', max_length=255),
            preserve_default=False,
        ),
    ]
